bug fixes for vmid, timezone, ipv6, balloon memory, importing disk, sshkeys
maxfield-allison/scripts pull request #5
Opened 2024-12-26 17:59 UTC by si458

2025-04-03 09:07 UTC, si458 commented
@maxfield-allison can this be merged at all to fix a few issues with your script?

2025-04-03 12:49 UTC, maxfield-allison commented
Let me take a look. apologies for the delay

2025-04-03 13:26 UTC, maxfield-allison requested changes
noted a few things, please review and let me know your thoughts.

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
> +    echo "  -t, --timezone   Set a timezone (default: 'Europe/London')."
Please update the default timezone from `"Europe/London"` to `"UTC"` in both the usage text and the variable initialization.

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
>      echo "  -s, --sshkeys    Set SSH keys for the cloud-init user."
realizing in script, this is the -k flag not the -s lfag

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
> +           --vmid) VMID="$2"; shift ;;
Let's add the flag `-v` and include it in help text.

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
> +    wget "$IMAGE_URL"
Since my environment requires IPv4, please add an optional flag (for example, `-p, --ipv4`, ) that, when set, will append the `--inet4-only` option to the wget command. By default, the script should behave as it does in your PR without forcing IPv4.

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
assuming this was thoroughly tested but would like confirmation. I can get to it sometime this weekend.

2025-04-03 13:26 UTC, maxfield-allison commented on proxmox-template-create.sh
thank you...........

2025-04-27 15:26 UTC, si458 commented
all done, also updated to 24.04 too as thats the latest LTS build now :)

2025-07-24 20:11 UTC, si458 commented
@maxfield-allison ping hehe

2025-07-24 22:31 UTC, maxfield-allison approved these changes
Sorry for the delay!

2025-07-24 22:31 UTC, merged

2025-07-24 23:03 UTC, si458 commented
Sure no worries! I hadn't used it in awhile then needed to use it before and remembered myself I had a pr open haha